<a href="https://colab.research.google.com/github/hruthiksiva/recommendation-system/blob/main/recommedation_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("ahsanaseer/top-rated-tmdb-movies-10k")

print("Path to dataset files:", path)

Downloading from https://www.kaggle.com/api/v1/datasets/download/ahsanaseer/top-rated-tmdb-movies-10k?dataset_version_number=1...

100%|██████████| 1.43M/1.43M [00:00<00:00, 94.8MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/ahsanaseer/top-rated-tmdb-movies-10k/versions/1

In [2]:
import pandas as pd

In [29]:
df = pd.read_csv(path+'/top10K-TMDB-movies.csv')

In [30]:
df.head()

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 10000 non-null  int64
 1   title              10000 non-null  object
 2   genre              9997 non-null   object
 3   original_language  10000 non-null  object
 4   overview           9987 non-null   object
 5   popularity         10000 non-null  float64
 6   release_date       10000 non-null  object
 7   vote_average       10000 non-null  float64
 8   vote_count         10000 non-null  int64
dtypes: float64(2), int64(2), object(5)
memory usage: 703.2+ KB

In [7]:
df['original_language'].unique()

array(['en', 'hi', 'es', 'ja', 'ko', 'it', 'pt', 'ru', 'zh', 'fr', 'tr',
       'sv', 'ar', 'de', 'bn', 'cn', 'da', 'nl', 'th', 'fa', 'hu', 'pl',
       'sh', 'sr', 'et', 'id', 'no', 'cs', 'te', 'ro', 'bs', 'el', 'fi',
       'is', 'ml', 'la', 'af', 'uk', 'eu', 'nb', 'he', 'ab', 'xx'],
      dtype=object)

In [8]:
# content based recommendation system
# collaborative based recommendation system

In [9]:
#cosine similarity

In [14]:
all_genres = set()
for genres in df['genre']:
  if isinstance(genres, str):
    for g in genres.split(','):
      all_genres.add(g)

In [15]:
all_genres

{'Action',
 'Adventure',
 'Animation',
 'Comedy',
 'Crime',
 'Drama',
 'Family',
 'Fantasy',
 'History',
 'Horror',
 'Music',
 'Mystery',
 'Romance',
 'Science Fiction',
 'TV Movie',
 'Thriller',
 'War',
 'Western'}

In [17]:
for genre in all_genres:
  df[genre] = df['genre'].apply(lambda x:1 if isinstance(x, str) and genre in x.split(',') else 0)
df

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count,Animation,...,Science Fiction,Comedy,Drama,Family,Western,TV Movie,Horror,Thriller,Action,Adventure
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862,0,...,0,0,1,0,0,0,0,0,0,0
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731,0,...,0,1,1,0,0,0,0,0,0,0
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280,0,...,0,0,1,0,0,0,0,0,0,0
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959,0,...,0,0,1,0,0,0,0,0,0,0
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,10196,The Last Airbender,"Action,Adventure,Fantasy",en,"The story follows the adventures of Aang, a yo...",98.322,2010-06-30,4.7,3347,0,...,0,0,0,0,0,0,0,0,1,1
9996,331446,Sharknado 3: Oh Hell No!,"Action,TV Movie,Science Fiction,Comedy,Adventure",en,The sharks take bite out of the East Coast whe...,12.490,2015-07-22,4.7,417,0,...,1,1,0,0,0,1,0,0,1,1
9997,13995,Captain America,"Action,Science Fiction,War",en,"During World War II, a brave, patriotic Americ...",18.333,1990-12-14,4.6,332,0,...,1,0,0,0,0,0,0,0,1,0
9998,2312,In the Name of the King: A Dungeon Siege Tale,"Adventure,Fantasy,Action,Drama",en,A man named Farmer sets out to rescue his kidn...,15.159,2007-11-29,4.7,668,0,...,0,0,1,0,0,0,0,0,1,1
9999,455957,Domino,"Thriller,Action,Crime",en,Seeking justice for his partner’s murder by an...,16.482,2019-05-31,4.6,221,0,...,0,0,0,0,0,0,0,1,1,0

In [19]:
from sklearn.metrics.pairwise import cosine_similarity

feature_vectors = df[list(all_genres)]

In [20]:
cosine_sim = cosine_similarity(feature_vectors)

In [22]:
cosine_sim[0][1]

0.408248290463863

In [ ]:
# using NLTK

In [32]:
df = df.dropna()
df

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811
...,...,...,...,...,...,...,...,...,...
9995,10196,The Last Airbender,"Action,Adventure,Fantasy",en,"The story follows the adventures of Aang, a yo...",98.322,2010-06-30,4.7,3347
9996,331446,Sharknado 3: Oh Hell No!,"Action,TV Movie,Science Fiction,Comedy,Adventure",en,The sharks take bite out of the East Coast whe...,12.490,2015-07-22,4.7,417
9997,13995,Captain America,"Action,Science Fiction,War",en,"During World War II, a brave, patriotic Americ...",18.333,1990-12-14,4.6,332
9998,2312,In the Name of the King: A Dungeon Siege Tale,"Adventure,Fantasy,Action,Drama",en,A man named Farmer sets out to rescue his kidn...,15.159,2007-11-29,4.7,668
9999,455957,Domino,"Thriller,Action,Crime",en,Seeking justice for his partner’s murder by an...,16.482,2019-05-31,4.6,221

In [33]:
df['tags'] = df['overview']+df['genre']
df['tags'] = df['tags'].apply(lambda x:x.lower())

In [34]:
df

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count,tags
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862,framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731,"raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280,"spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959,the true story of how businessman oskar schind...
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811,in the continuing saga of the corleone crime f...
...,...,...,...,...,...,...,...,...,...,...
9995,10196,The Last Airbender,"Action,Adventure,Fantasy",en,"The story follows the adventures of Aang, a yo...",98.322,2010-06-30,4.7,3347,"the story follows the adventures of aang, a yo..."
9996,331446,Sharknado 3: Oh Hell No!,"Action,TV Movie,Science Fiction,Comedy,Adventure",en,The sharks take bite out of the East Coast whe...,12.490,2015-07-22,4.7,417,the sharks take bite out of the east coast whe...
9997,13995,Captain America,"Action,Science Fiction,War",en,"During World War II, a brave, patriotic Americ...",18.333,1990-12-14,4.6,332,"during world war ii, a brave, patriotic americ..."
9998,2312,In the Name of the King: A Dungeon Siege Tale,"Adventure,Fantasy,Action,Drama",en,A man named Farmer sets out to rescue his kidn...,15.159,2007-11-29,4.7,668,a man named farmer sets out to rescue his kidn...
9999,455957,Domino,"Thriller,Action,Crime",en,Seeking justice for his partner’s murder by an...,16.482,2019-05-31,4.6,221,seeking justice for his partner’s murder by an...

In [35]:
df = df[['id','title','tags']]
df

,id,title,tags
0,278,The Shawshank Redemption,framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,the true story of how businessman oskar schind...
4,240,The Godfather: Part II,in the continuing saga of the corleone crime f...
...,...,...,...
9995,10196,The Last Airbender,"the story follows the adventures of aang, a yo..."
9996,331446,Sharknado 3: Oh Hell No!,the sharks take bite out of the east coast whe...
9997,13995,Captain America,"during world war ii, a brave, patriotic americ..."
9998,2312,In the Name of the King: A Dungeon Siege Tale,a man named farmer sets out to rescue his kidn...
9999,455957,Domino,seeking justice for his partner’s murder by an...

In [ ]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')